/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.poly.shopclothes;

import edu.poly.shopclothes.dao.NhanVienDao;
import edu.poly.shopclothes.entity.NhanVien;
import edu.poly.shopclothes.helper.DiaLogHelper;
import edu.poly.shopclothes.helper.ShereHelper;

/**
 *
 * @author pc
 */
public class DoiMatKhauJDialog extends javax.swing.JDialog {
    
    NhanVienDao dao = new NhanVienDao();

    /**
     * Creates new form DoiMatKhauJDialog
     */
    public DoiMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        init();
        ThongTinDMK9();
    }
    
    void init() {
        if (ShereHelper.USER != null) {
            
        } else {
            DiaLogHelper.alert(this, "Vui lòng đăng nhập");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassWord = new javax.swing.JPasswordField();
        txtPasswordNew = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        btnCANCEL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHANGE PASSWORD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("New password :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Enter the password:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Password :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 110, 20));

        txtNam.setBackground(new java.awt.Color(102, 102, 255));
        txtNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNam.setForeground(new java.awt.Color(255, 255, 255));
        txtNam.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNam.setName(""); // NOI18N
        jPanel2.add(txtNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 30));

        txtPassword2.setBackground(new java.awt.Color(102, 102, 255));
        txtPassword2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword2.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));

        txtPassWord.setBackground(new java.awt.Color(102, 102, 255));
        txtPassWord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassWord.setForeground(new java.awt.Color(255, 255, 255));
        txtPassWord.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));

        txtPasswordNew.setBackground(new java.awt.Color(102, 102, 255));
        txtPasswordNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordNew.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordNew.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txtPasswordNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 30));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-save-as-100.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 40));

        btnCANCEL.setBackground(new java.awt.Color(255, 255, 255));
        btnCANCEL.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btnCANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-cancel-64.png"))); // NOI18N
        btnCANCEL.setText("CANCEL");
        btnCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELActionPerformed(evt);
            }
        });
        jPanel2.add(btnCANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 160, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 390, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/juicy-boy-with-laptop-installing-security-passwords-shield-and-lock-on-his-pc-and-phone.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 270));

        jLabel3.setFont(new java.awt.Font("Barlow Condensed SemiBold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("ShopClothes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-password-64.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 40, -1));

        jLabel5.setFont(new java.awt.Font("Barlow Condensed SemiBold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("FPT POLYTECHNIC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCANCELActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        doiMatKhau();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhauJDialog dialog = new DoiMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCANCEL;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNam;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JPasswordField txtPasswordNew;
    // End of variables declaration//GEN-END:variables
//
//    
//     void doiMatKhau(){
//        
////     String manv = txtNam.getText();
////     String matkhaumoi = new String(txtPasswordNew.getPassword());
////     String matkhau = new String(txtPassWord.getPassword());
////     String matkhaumoi2 = new String(txtPassword2.getPassword());
////       NhanVien nhanvien = dao.selectById(manv);
////      
////     //equalsIgnoreCase
////     
////    if(!manv.equalsIgnoreCase(nhanvien.getMaNV())){
////        DiaLogHelper.alert(this, "Sai Tên Đăng Nhập !");
////    } else if(!matkhau.equals(nhanvien.getMatKhau())){
////        DiaLogHelper.alert(this,"Sai Mật Khẩu");
////    }
////    else if(!matkhaumoi.equals(matkhaumoi2)){
////        DiaLogHelper.alert(this,"Xác Nhận Mật Khẩu Không Đúng ");
////    }else{
////       nhanvien.setMatKhau(matkhaumoi);
////        dao.update(nhanvien);
////        DiaLogHelper.alert(this, "Đổi Mât Khẩu Thành Công !! ");
////    }
//}
    void ThongTinDMK9() {
        txtNam.setText(ShereHelper.USER.getMaNV());
        txtPassWord.setText(ShereHelper.USER.getMatKhau());
    }

    void doiMatKhau() {
        
        String manv = txtNam.getText();
        String matkhaumoi = new String(txtPasswordNew.getPassword());
        String matkhau = new String(txtPassWord.getPassword());
        String matkhaumoi2 = new String(txtPassword2.getPassword());
        NhanVien nhanvien = dao.selectById(manv);
        if (nhanvien != null) {
            if (!matkhau.equals(nhanvien.getMatKhau())) {
                DiaLogHelper.alert(this, "Sai Mật Khẩu");
                
            } else if (!matkhaumoi.equals(matkhaumoi2)) {
                DiaLogHelper.alert(this, "Xác Nhận Mật Khẩu Không Đúng ");
            } else {
                nhanvien.setMatKhau(matkhaumoi);
                dao.update(nhanvien);
                DiaLogHelper.alert(this, "Đổi Mât Khẩu Thanh cong");
            }
            
        } else {
            DiaLogHelper.alert(this, "Sai tên Đăng Nhập !!");
        }
    }
    
}
