/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.poly.shopclothes;

import edu.poly.shopclothes.dao.HoaDonCTDao;
import edu.poly.shopclothes.dao.HoaDonDao;
import edu.poly.shopclothes.entity.HoaDon;
import edu.poly.shopclothes.entity.HoaDonCT;
import edu.poly.shopclothes.helper.DiaLogHelper;
import edu.poly.shopclothes.helper.XDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class HoaDonlFrame extends javax.swing.JInternalFrame {
    int index =0;
    HoaDonDao dao = new HoaDonDao();
    HoaDonCTDao ctdao = new HoaDonCTDao();

    /**
     * Creates new form HoaDonlFrame
     */
    public HoaDonlFrame() {
        initComponents();
             this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        
    
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        intiTable();
        intiTable2();
        fillTable();
    }
    
    private void intiTable(){
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String []{"Mã HD","Mã NV","Tổng Tiền","Tiền Khách Đứa","Tiền Thừa","Hinh Thực TT","Ngày Lập"});  
        tblHoaDon.setModel(model);
       
    }
        private void intiTable2(){
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String []{"Mã HD","Mã SP","Tên SP","Số Lượng","Đơn Giá"});  
        tblHDChithiet.setModel(model);
       
    }
    
    private void fillTable(){
        DefaultTableModel model =(DefaultTableModel)tblHoaDon.getModel();
        model.setRowCount(0);
        
        List<HoaDon>list=dao.selectAll();
        for (HoaDon hd : list) {
            Object row[]={hd.getMaHD(),hd.getMaNV(),hd.getTongTien(),hd.getTienKhachTra(),hd.getTienThua(),hd.getHinhThucTT(),XDate.toString(hd.getNgayLap(),"dd/MM/yyyy")};
            model.addRow(row);
            
        }
    }
        
        private void TimKiemTheoT(){
        DefaultTableModel model =(DefaultTableModel)tblHoaDon.getModel();
        model.setRowCount(0);
        Integer maHD=Integer.valueOf(txtTimK.getText());
        List<HoaDon>list=dao.selectByKeyWord(maHD);
        for (HoaDon hd : list) {
            Object row[]={hd.getMaHD(),hd.getMaNV(),hd.getTongTien(),hd.getTienKhachTra(),hd.getTienThua(),hd.getHinhThucTT(),XDate.toString(hd.getNgayLap(),"dd/MM/yyyy")};
            model.addRow(row);
            
        }
        
        
        
        
        
        
       
                
                
    }
    private void SelectHDChiTiet(){
        DefaultTableModel model=(DefaultTableModel)tblHDChithiet.getModel();
        model.setRowCount(0);
        Integer MaHD=(Integer)tblHoaDon.getValueAt(this.index,0);
        List<HoaDonCT> list=ctdao.SelcetTheoHD(MaHD);
        for (HoaDonCT ct : list) {
            Object row[]={ct.getMAHD(),ct.getMaSP(),ct.getTenSP(),ct.getSoLuong(),ct.getGiaTien()};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTimK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        tbnTimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDChithiet = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtTimK, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 340, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Tìm Kiếm Hóa Đơn");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 110, 30));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblHoaDon.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tblHoaDon.setShowGrid(true);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1070, 250));

        tbnTimKiem.setBackground(new java.awt.Color(255, 153, 0));
        tbnTimKiem.setText("Tìm");
        tbnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(tbnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 380));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn CT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHDChithiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHDChithiet.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane2.setViewportView(tblHDChithiet);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1070, 260));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1090, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblHoaDon.rowAtPoint(evt.getPoint());

            if (DiaLogHelper.showConfirmDialog(this, "Bạn Có Muốn Xem Hoa Đơn CT ?", "Trả Lời") == JOptionPane.NO_OPTION) {
                return;
            } else {
                this.SelectHDChiTiet();
            }

        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tbnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnTimKiemActionPerformed
        // TODO add your handling code here:
        this.TimKiemTheoT();
    }//GEN-LAST:event_tbnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHDChithiet;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JButton tbnTimKiem;
    private javax.swing.JTextField txtTimK;
    // End of variables declaration//GEN-END:variables
}
