/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.poly.shopclothes;

import edu.poly.shopclothes.dao.KhachHangDao;
import edu.poly.shopclothes.entity.KhachHang;
import edu.poly.shopclothes.helper.DiaLogHelper;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class KhachHanglFrame extends javax.swing.JInternalFrame {

    KhachHangDao daokh = new KhachHangDao();
    int index = 0;

    /**
     * Creates new form KhachHanglFrame
     */
    public KhachHanglFrame() {
        initComponents();
        init();
        intiTable();
        fillTable();

    }

    private void init() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    private void intiTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Mã KH", "Tên KH", "SỐ ĐT", "Giới Tính", "Email", "Địa Chỉ", "Trang Thái"});
        tblKhachHang.setModel(model);

    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);

        try {
            List<KhachHang> list = daokh.selectAll();
            for (KhachHang kh : list) {
                Object[] row = {kh.getMaKH(), kh.getTenKH(), kh.getSoDT(), kh.isGioiTinh() ? "Nam" : "Nữ", kh.getEmail(), kh.getDiaChi(), kh.getTrangThai()};
                model.addRow(row);

            }

        } catch (Exception e) {
            DiaLogHelper.alert(this, e.getMessage());
        }

    }

    private void setForm(KhachHang kh) {
        txtMaKH.setText(kh.getMaKH());
        txtTenKH.setText(kh.getTenKH());
        txtSoDT.setText(kh.getSoDT());
        cboGioiTinh.setSelectedIndex(kh.isGioiTinh() ? 0 : 1);
        txtEmail.setText(kh.getEmail());
        txtDiaChi.setText(kh.getDiaChi());
        txtTrangThai.setText(kh.getTrangThai());
    }

    private KhachHang getForm() {
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKH.getText());
        kh.setTenKH(txtTenKH.getText());
        kh.setSoDT(txtSoDT.getText());
        kh.setGioiTinh(cboGioiTinh.getSelectedIndex() == 0);
        kh.setEmail(txtEmail.getText());
        kh.setDiaChi(txtDiaChi.getText());
        kh.setTrangThai(txtTrangThai.getText());
        return kh;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        cboGioiTinh = new javax.swing.JComboBox<>();
        txtTrangThai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimTheoTen = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLocDiaChi = new javax.swing.JTextField();
        btnTimTheoDC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setBackground(new java.awt.Color(255, 153, 51));
        btnNew.setText("Làm Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 110, -1));

        btnSua.setBackground(new java.awt.Color(255, 153, 51));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 110, -1));

        btnXoa.setBackground(new java.awt.Color(255, 153, 51));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Làm Mới");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 110, -1));

        jButton7.setText("Sửa");
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 110, -1));

        jButton8.setText("Xóa");
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, -1));

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel5.setText("Họ Tên KH");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 20));

        jLabel14.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel14.setText("Địa Chỉ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 70, 20));

        jLabel16.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel16.setText("Mã KH");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 20));

        jLabel17.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel17.setText("Giới Tính");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 20));

        jLabel18.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel18.setText("Trang Thái");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 70, 20));

        jLabel19.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel19.setText("SoDT");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 70, 20));

        jLabel20.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel20.setText("Email");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 70, 20));
        jPanel4.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, 30));
        jPanel4.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, 30));
        jPanel4.add(txtSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 250, 30));
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 250, 30));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 196, 250, 70));

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel4.add(cboGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        jPanel4.add(txtTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 250, 30));

        btnThem.setBackground(new java.awt.Color(255, 153, 51));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel4.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 110, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 320));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 320));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseEntered(evt);
            }
        });
        jPanel3.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 290, 30));

        btnTimTheoTen.setBackground(new java.awt.Color(0, 204, 204));
        btnTimTheoTen.setText("Tìm");
        btnTimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoTenActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 410, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Địa Chỉ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));
        jPanel5.add(txtLocDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 240, 30));

        btnTimTheoDC.setBackground(new java.awt.Color(0, 204, 204));
        btnTimTheoDC.setText("Tìm");
        btnTimTheoDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoDCActionPerformed(evt);
            }
        });
        jPanel5.add(btnTimTheoDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 410, 60));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhachHang.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1080, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtMaKH.setText("");
        txtDiaChi.setText("");
        txtEmail.setText(" ");
        txtTimKiem.setText("");
        txtTrangThai.setText("");
        txtTenKH.setText("");
        txtSoDT.setText("");
        cboGioiTinh.setSelectedIndex(0);
        flag =false;

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        check();
        if (flag==true) {

            insert();
            flag=false;
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblKhachHang.rowAtPoint(evt.getPoint());
            this.edit();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//      check();
//      if(flag==true){
//          this.update();
//      }
        this.update();
        //txtMaKH.setEnabled(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimTheoDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoDCActionPerformed
        // TODO add your handling code here:
        this.TimKiemDC();
    }//GEN-LAST:event_btnTimTheoDCActionPerformed

    private void btnTimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoTenActionPerformed
        this.TimKiemKH();
    }//GEN-LAST:event_btnTimTheoTenActionPerformed

    private void txtTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseEntered
        // TODO add your handling code here:
        this.TimKiemKH();
    }//GEN-LAST:event_txtTimKiemMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimTheoDC;
    private javax.swing.JButton btnTimTheoTen;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLocDiaChi;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
 private void insert() {
        KhachHang kh = getForm();
        String MaKH = txtMaKH.getText();
        KhachHang khachhang = daokh.selectById(MaKH);
        if (khachhang != null) {
            DiaLogHelper.alert(this, "Mã KH đã tồn Tại !! ");

        } else {
            try {
                daokh.insert(kh);
                DiaLogHelper.alert(this, "Thêm Mới Khách Hàng Thành  Công");
                fillTable();
            } catch (Exception e) {
                DiaLogHelper.alert(this, e.getMessage());
            }

        }
    }

    private void update() {
        KhachHang kh = getForm();
        String MaKH = txtMaKH.getText();
        KhachHang khachhang = daokh.selectById(MaKH);
          if (DiaLogHelper.confirm(this, "Bạn có muốn cập nhật thông tin khách hàng này")) {
        if (khachhang != null) {
            try {
                daokh.update(kh);
                fillTable();
                DiaLogHelper.alert(this, "Cập nhât thông tin khách hàng thành công ! ");
            } catch (Exception e) {
                DiaLogHelper.showErrorDialog(this, e.getMessage(), "Lỗi Truy Vẫn Dữ Liệu !!");
            }

        } else {
            DiaLogHelper.alert(this, "Mã KH Ko Tồn Tại");
        }
          }

    }

    private void delete() {
        String MaKH = txtMaKH.getText();
        KhachHang khachhang = daokh.selectById(MaKH);
          if (DiaLogHelper.confirm(this, "Bạn có muốn xoá khách hàng này")) {
        try {
            if (khachhang != null) {
                daokh.delete(MaKH);
                fillTable();
                DiaLogHelper.alert(this, "Xóa KH thành công !! ");

            } else {
                DiaLogHelper.alert(this, "Mã KH ko tồn tại !! ");
            }
        } catch (Exception e) {
            DiaLogHelper.showErrorDialog(this, e.getMessage(), "Lỗi truy vẫn dữ liệu !! ");
        }

    }
    }

    private void edit() {
        String MaKH = (String) tblKhachHang.getValueAt(this.index, 0);
        KhachHang kh = daokh.selectById(MaKH);
        this.setForm(kh);

    }
//   private void edit() {
//        String manv = (String) tblNguoiHoc.getValueAt(this.row, 0);
//        NguoiHoc nv = dao.selectById(manv);
//        this.setForm(nv);
//        tabs.setSelectedIndex(0);
//        this.updateStatus();
//
//    }

    boolean flag = false;

    void check() {

        if ((txtMaKH.getText()).length() < 5 || (txtMaKH.getText()).length() > 5) {
            if ((txtMaKH.getText()).equals("")) {
                DiaLogHelper.alert(this, "Mã người học không được để trống");

            } else {
                DiaLogHelper.alert(this, "Mã người học phải nhập đúng 5 ký tự");
            }
            
        } else if ((txtTenKH.getText()).equals("")) {
            DiaLogHelper.alert(this, "Họ tên không được để trống");
//        } else if (!txtTenKH.getText().matches("[a-zA-Z][a-zA-Z ]+")) {
//            DiaLogHelper.alert(this, "Họ tên chỉ chứa alphabet và ký tự trắng");
            
        } else if (txtSoDT.getText().equals("")) {
            DiaLogHelper.alert(this, "Số điện thoại không được để trống");
        } else if (txtSoDT.getText().length() < 9 || txtSoDT.getText().length() > 13) {
            DiaLogHelper.alert(this, "Số điện thoại phải nhập đủ 10 hoặc 11 số.");
        } else if (!txtSoDT.getText().matches("[0-9]+")) {

            DiaLogHelper.alert(this, "Số điện thoại chỉ nhập số");
         
        } else if (txtEmail.getText().equals("")) {
            DiaLogHelper.alert(this, "Email không đươc để trống");
           

//        } else if (txtNgaySinh.getText().equals("")) {
//            DiaLogHelper.alert(this, "Ngày sinh không đươc để trống");
//        }
        }else{
            flag=true;
        }
        
    }

    private void TimKiemKH() {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        String TenNV = txtTimKiem.getText();
        List<KhachHang> list = daokh.selectByKeyWord(TenNV);
        for (KhachHang kh : list) {
            Object[] row = {kh.getMaKH(), kh.getTenKH(), kh.getSoDT(), kh.isGioiTinh() ? "Nam" : "Nữ", kh.getEmail(), kh.getDiaChi(), kh.getTrangThai()};
            model.addRow(row);

        }

    }

    private void TimKiemDC() {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        String DiaChi = txtLocDiaChi.getText();
        List<KhachHang> list = daokh.selectByDiaChi(DiaChi);
        for (KhachHang kh : list) {
            Object[] row = {kh.getMaKH(), kh.getTenKH(), kh.getSoDT(), kh.isGioiTinh() ? "Nam" : "Nữ", kh.getEmail(), kh.getDiaChi(), kh.getTrangThai()};
            model.addRow(row);

        }

    }

}
