/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.poly.shopclothes;

import edu.poly.shopclothes.helper.XLmage;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author pc
 */
public class ShopClothesJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShopClothesJFrame
     */
    
    
//     Border deafau_border = BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(51,51,51));
//    Border yellow_border = BorderFactory.createMatteBorder(1, 0, 1, 0, Color.BLACK);
    JLabel[] menuLabels = new JLabel[7];
    public ShopClothesJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        Mini_DangXuatMouseClicked(null);
        mini_BangHangMouseClicked(null);
        addActionMenuLabels();
        init();
        
        
        menuLabels[0] = mini_BangHang;
        menuLabels[1] = mini_SanPham;
        menuLabels[2] = mini_HoaDon;
        menuLabels[3] = mini_NhanVien;
        menuLabels[4] = mini_KhachHang;
        menuLabels[5] = mini_ThongKe;
        menuLabels[6] =Mini_DangXuat;
        
        
       
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanMain = new javax.swing.JPanel();
        PanMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tblThongtin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDoimk = new javax.swing.JLabel();
        Mini_DangXuat = new javax.swing.JLabel();
        mini_BangHang = new javax.swing.JLabel();
        mini_SanPham = new javax.swing.JLabel();
        mini_HoaDon = new javax.swing.JLabel();
        mini_NhanVien = new javax.swing.JLabel();
        mini_KhachHang = new javax.swing.JLabel();
        mini_ThongKe = new javax.swing.JLabel();
        PenFood = new javax.swing.JPanel();
        tblDongHo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanMain.setBackground(new java.awt.Color(255, 255, 255));
        PanMain.setMinimumSize(new java.awt.Dimension(1300, 750));
        PanMain.setPreferredSize(new java.awt.Dimension(1300, 750));
        PanMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanMenu.setBackground(new java.awt.Color(233, 183, 17));
        PanMenu.setPreferredSize(new java.awt.Dimension(180, 700));
        PanMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblThongtin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblThongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-user-100.png"))); // NOI18N
        tblThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongtinMouseClicked(evt);
            }
        });
        jPanel3.add(tblThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hồ Văn Hải ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 26));

        btnDoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-password-64.png"))); // NOI18N
        btnDoimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoimkMouseClicked(evt);
            }
        });
        jPanel3.add(btnDoimk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 189, 180));

        Mini_DangXuat.setBackground(new java.awt.Color(233, 183, 17));
        Mini_DangXuat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Mini_DangXuat.setForeground(new java.awt.Color(51, 51, 51));
        Mini_DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mini_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/login (1).png"))); // NOI18N
        Mini_DangXuat.setText("Đăng Xuất");
        Mini_DangXuat.setOpaque(true);
        Mini_DangXuat.setPreferredSize(new java.awt.Dimension(180, 50));
        Mini_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mini_DangXuatMouseClicked(evt);
            }
        });
        PanMenu.add(Mini_DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 190, -1));

        mini_BangHang.setBackground(new java.awt.Color(233, 183, 17));
        mini_BangHang.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_BangHang.setForeground(new java.awt.Color(51, 51, 51));
        mini_BangHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_BangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/clothes-shop.png"))); // NOI18N
        mini_BangHang.setText("Bán Hàng");
        mini_BangHang.setOpaque(true);
        mini_BangHang.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_BangHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_BangHangMouseClicked(evt);
            }
        });
        PanMenu.add(mini_BangHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, -1));

        mini_SanPham.setBackground(new java.awt.Color(233, 183, 17));
        mini_SanPham.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_SanPham.setForeground(new java.awt.Color(51, 51, 51));
        mini_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/box.png"))); // NOI18N
        mini_SanPham.setText("Sản Phẩm");
        mini_SanPham.setOpaque(true);
        mini_SanPham.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_SanPhamMouseClicked(evt);
            }
        });
        PanMenu.add(mini_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, -1));

        mini_HoaDon.setBackground(new java.awt.Color(233, 183, 17));
        mini_HoaDon.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_HoaDon.setForeground(new java.awt.Color(51, 51, 51));
        mini_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-cheque-48.png"))); // NOI18N
        mini_HoaDon.setText("Hóa Đơn");
        mini_HoaDon.setOpaque(true);
        mini_HoaDon.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_HoaDonMouseClicked(evt);
            }
        });
        PanMenu.add(mini_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, -1));

        mini_NhanVien.setBackground(new java.awt.Color(233, 183, 17));
        mini_NhanVien.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_NhanVien.setForeground(new java.awt.Color(51, 51, 51));
        mini_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/man.png"))); // NOI18N
        mini_NhanVien.setText("Nhân Viên");
        mini_NhanVien.setOpaque(true);
        mini_NhanVien.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_NhanVienMouseClicked(evt);
            }
        });
        PanMenu.add(mini_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, -1));

        mini_KhachHang.setBackground(new java.awt.Color(233, 183, 17));
        mini_KhachHang.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_KhachHang.setForeground(new java.awt.Color(51, 51, 51));
        mini_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/team.png"))); // NOI18N
        mini_KhachHang.setText("Khách Hàng");
        mini_KhachHang.setOpaque(true);
        mini_KhachHang.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_KhachHangMouseClicked(evt);
            }
        });
        PanMenu.add(mini_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 190, -1));

        mini_ThongKe.setBackground(new java.awt.Color(233, 183, 17));
        mini_ThongKe.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mini_ThongKe.setForeground(new java.awt.Color(51, 51, 51));
        mini_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/analytics.png"))); // NOI18N
        mini_ThongKe.setText("Thống Kê");
        mini_ThongKe.setOpaque(true);
        mini_ThongKe.setPreferredSize(new java.awt.Dimension(180, 50));
        mini_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_ThongKeMouseClicked(evt);
            }
        });
        PanMenu.add(mini_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 190, -1));

        PanMain.add(PanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 189, 719));

        PenFood.setBackground(new java.awt.Color(153, 153, 255));
        PenFood.setPreferredSize(new java.awt.Dimension(31, 31));
        PenFood.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDongHo.setForeground(new java.awt.Color(255, 153, 51));
        tblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-cloud-clock-100.png"))); // NOI18N
        tblDongHo.setText("00:00");
        PenFood.add(tblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 170, 30));

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/shopclothes/icon/icons8-duolingo-logo-100.png"))); // NOI18N
        jLabel3.setText("Hệ Thống Shop Quần Áo Nhóm 5");
        PenFood.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        PanMain.add(PenFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1290, 40));

        DesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        PanMain.add(DesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1100, 720));

        getContentPane().add(PanMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mini_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mini_DangXuatMouseClicked
        this.dispose();
        LoginJDialog login= new LoginJDialog(this, true);
        login.setVisible(true);
        
    }//GEN-LAST:event_Mini_DangXuatMouseClicked

    private void btnDoimkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoimkMouseClicked
       DoiMatKhauJDialog doimk= new DoiMatKhauJDialog(this,true);
       doimk.setVisible(true);
    }//GEN-LAST:event_btnDoimkMouseClicked

    private void mini_BangHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_BangHangMouseClicked
         BanHanglFrame menu1 = new BanHanglFrame();
        DesktopPane1.removeAll();
        DesktopPane1.add(menu1).setVisible(true);
    }//GEN-LAST:event_mini_BangHangMouseClicked

    private void mini_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_NhanVienMouseClicked
       NhanVienlFrame nhanvien = new NhanVienlFrame();
       DesktopPane1.removeAll();
       DesktopPane1.add(nhanvien).setVisible(true);
    }//GEN-LAST:event_mini_NhanVienMouseClicked

    private void mini_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_SanPhamMouseClicked
        SanPhamlFrame sanpham = new SanPhamlFrame();
        DesktopPane1.removeAll();
        DesktopPane1.add(sanpham).setVisible(true);
    }//GEN-LAST:event_mini_SanPhamMouseClicked

    private void mini_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_KhachHangMouseClicked
       KhachHanglFrame khachhang = new KhachHanglFrame();
       DesktopPane1.removeAll();
       DesktopPane1.add(khachhang).setVisible(true);
    }//GEN-LAST:event_mini_KhachHangMouseClicked

    private void mini_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_ThongKeMouseClicked
       ThongKelFrame thongke = new ThongKelFrame();
       DesktopPane1.removeAll();
       DesktopPane1.add(thongke).setVisible(true);
    }//GEN-LAST:event_mini_ThongKeMouseClicked

    private void mini_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_HoaDonMouseClicked
        HoaDonlFrame hoadon = new HoaDonlFrame();
        DesktopPane1.removeAll();
        DesktopPane1.add(hoadon).setVisible(true);
    }//GEN-LAST:event_mini_HoaDonMouseClicked

    private void tblThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongtinMouseClicked
        // TODO add your handling code here:
        ThongTinNhanVienJFrame tt = new ThongTinNhanVienJFrame();
        tt.setVisible(true);
    }//GEN-LAST:event_tblThongtinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopClothesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopClothesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopClothesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopClothesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopClothesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane1;
    private javax.swing.JLabel Mini_DangXuat;
    private javax.swing.JPanel PanMain;
    private javax.swing.JPanel PanMenu;
    private javax.swing.JPanel PenFood;
    private javax.swing.JLabel btnDoimk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mini_BangHang;
    private javax.swing.JLabel mini_HoaDon;
    private javax.swing.JLabel mini_KhachHang;
    private javax.swing.JLabel mini_NhanVien;
    private javax.swing.JLabel mini_SanPham;
    private javax.swing.JLabel mini_ThongKe;
    private javax.swing.JLabel tblDongHo;
    private javax.swing.JLabel tblThongtin;
    // End of variables declaration//GEN-END:variables
private  void init(){
 
         this.setIconImage(XLmage.getAppIcon());
    
    // donh ho
       new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date now = new Date();
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
            String test = format.format(now);
            tblDongHo.setText(test);
            
           
        }
        
       }).start();
           
         
     }
    
       
     public void setLabelBackrou(JLabel label) {
      
        
        for (JLabel menuItem : menuLabels) {
        menuItem.setBackground(new Color(233,183,17));
        menuItem.setForeground(new Color(51,51,51));   
        
        }
        label.setBackground(new Color(210,194,140));
        label.setForeground(new Color(102,102,102));

        
    }
      
      
   
    
    public void addActionMenuLabels() {
        Component[] components = PanMenu.getComponents();
        for (Component component : components) {

            if (component instanceof JLabel) {
                JLabel label = (JLabel) component;

                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setLabelBackrou(label);

                    }

                    @Override
                    public void mousePressed(MouseEvent e) {

                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
//                        label.setBorder(yellow_border);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
//                        label.setBorder(deafau_border);
                    }
                });

            }
        }
    }
    




}
