/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.poly.shopclothes;

import edu.poly.shopclothes.dao.HoaDonDao;
import edu.poly.shopclothes.dao.ThongKeDao;
import edu.poly.shopclothes.entity.HoaDon;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ThongKelFrame extends javax.swing.JInternalFrame {
    ThongKeDao tkDao = new ThongKeDao();
    HoaDonDao hdDao = new HoaDonDao();
            
    /**
     * Creates new form ThongKelFrame
     */
    public ThongKelFrame() {
        initComponents();
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        
    
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
       fillComBoxNam();
      fillComBoxNam2();
     // fillTableTheoThang();
    }
    
    
    void init(){
        
        
    }
    
    
    void fillComBoxNam(){
        DefaultComboBoxModel model=(DefaultComboBoxModel) cboNam.getModel();
          model.removeAllElements();
        List<HoaDon> list=hdDao.selectAll();
        for (HoaDon kh : list) {
            int nam =kh.getNgayLap().getYear()+1900;
            if(model.getIndexOf(nam)<0){
                model.addElement(nam);
            }
            
        }
        cboNam.setSelectedIndex(0);
    }
       void fillComBoxNam2(){
        DefaultComboBoxModel model=(DefaultComboBoxModel) cboNam2.getModel();
        model.removeAllElements();
        List<HoaDon> list=hdDao.selectAll();
        for (HoaDon kh : list) {
            int nam =kh.getNgayLap().getYear()+1900;
            if(model.getIndexOf(nam)<0){
                model.addElement(nam);
            }
            
        }
        cboNam2.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tblKhachHang = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tblDTTuan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tblDoanhThuT = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboNam2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTKNam = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKSanPham = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống Kê Doanh Thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel4.setText("Khách Hàng");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 13, -1, -1));

        tblKhachHang.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 36)); // NOI18N
        tblKhachHang.setForeground(new java.awt.Color(255, 51, 0));
        tblKhachHang.setText("13");
        jPanel6.add(tblKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 280, 120));

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setText("Tuân Này");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 13, -1, -1));

        tblDTTuan.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 36)); // NOI18N
        tblDTTuan.setForeground(new java.awt.Color(255, 51, 0));
        tblDTTuan.setText("450.000");
        jPanel7.add(tblDTTuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("VND");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, 120));

        jPanel8.setBackground(new java.awt.Color(255, 204, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel3.setText("Tháng Này");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 13, -1, -1));

        tblDoanhThuT.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 36)); // NOI18N
        tblDoanhThuT.setForeground(new java.awt.Color(255, 51, 0));
        tblDoanhThuT.setText("2.000.000");
        jPanel8.add(tblDoanhThuT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("VND");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 290, 120));

        jLabel2.setText("Năm");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 20));

        cboNam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021" }));
        cboNam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNam2ActionPerformed(evt);
            }
        });
        jPanel2.add(cboNam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));

        tblTKNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblTKNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tổng HD", "Tổng SP Bán Đươc", "Doanh Thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTKNam.setGridColor(new java.awt.Color(255, 153, 0));
        tblTKNam.setRowHeight(20);
        tblTKNam.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblTKNam);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 810, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 320));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Theo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Năm");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020" }));
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });
        jPanel5.add(cboNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 410, 60));

        tblTKSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Đã Bán", "Doanh Thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTKSanPham.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(tblTKSanPham);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1080, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNam2ActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThu();
    }//GEN-LAST:event_cboNam2ActionPerformed

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
      fillTableSanPham();
    }//GEN-LAST:event_cboNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboNam2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tblDTTuan;
    private javax.swing.JLabel tblDoanhThuT;
    private javax.swing.JLabel tblKhachHang;
    private javax.swing.JTable tblTKNam;
    private javax.swing.JTable tblTKSanPham;
    // End of variables declaration//GEN-END:variables

    
      void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tblTKNam.getModel();
        model.setRowCount(0);
       
        if(cboNam.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this,"Ban Ko Chọn");
            return;
        }else{
             int nam = Integer.parseInt(cboNam.getSelectedItem().toString());
               List<Object[]> list =tkDao.getDoanhThu(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
        }
      

    }
      
      
      
          void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblTKSanPham.getModel();
        model.setRowCount(0);
       
        if(cboNam.getSelectedItem()==null){
            //JOptionPane.showMessageDialog(this,"Ban Ko Chọn");
            return;
        }else{
             int nam = Integer.parseInt(cboNam2.getSelectedItem().toString());
               List<Object[]> list =tkDao.getTopSPBanChay(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
        }
      

    }
          
              void fillTableTheoThang() {
//        DefaultTableModel model = (DefaultTableModel) tblTKSanPham.getModel();
//        model.setRowCount(0);
       
          double DoanhThu =tkDao.getTK();
          tblDoanhThuT.setText(DoanhThu+"VND");
          
//             int nam = Integer.parseInt(cboNam2.getSelectedItem().toString());
//            List<Object[]> list =tkDao.getTKTheoThang();
//                 list.get(0);
//                  System.out.println("Thang DThu"+list.get(0).toString());
//            
//        for (Object[] row : list) {
//            
//            tblDoanhThuT.setText(list.add(row));
//           // model.addRow(row);
//        }
        
    //  txtTenSP.setText(sp.getTenSP());

    }
          
          
                
  


}
